### PR TITLE
moved packages around

### PR DESCRIPTION
**Pull request by xh3b4sd**
This PR moves packages around. The structure looks like this now. 

```
$ tree -L 2 -d
.
├── client
│   ├── crdclient
│   └── k8s
├── context
│   ├── canceledcontext
│   ├── deletionallowedcontext
│   ├── updateallowedcontext
│   └── updatenecessarycontext
├── crd
│   └── fake
├── framework
├── informer
├── resource
│   ├── logresource
│   ├── metricsresource
│   └── retryresource
├── tpr
└── vendor
    ├── github.com
    ├── golang.org
    ├── gopkg.in
    └── k8s.io
```

The context packages are in the `context` folder and the resource packages are in the `resource` folder.

### CODE REVIEW

**Comment by kopiczko** [comment]
Do `context` and `resource` make sense on their own? I think they were framework specific and they should stay there.

I'd be happy to flatten what's inside `context` and `resource` packages though. I think it'd make coding experience nicer. I'd like to type `resource.New` and see what autocompletion has to offer.

**Comment by xh3b4sd** [comment]
> Do context and resource make sense on their own?

IMO yes. Observing what is inside a directory is way more easy when a folder bundles packages that serve under the same scope. 

> I'd be happy to flatten what's inside context and resource packages though.

I am not a fan of packages that provide different implementations. IMO one implementation per package makes a lot of sense. I do not like polluting the package namespace. Names just get longer and more complicated.

**Comment by kopiczko** [comment]
>> Do context and resource make sense on their own?
>
>IMO yes. Observing what is inside a directory is way more easy when a folder bundles packages that serve under the same scope.

We didn't understand each other. I'm fine with `resource` bundling the rest.
I asking if `resource` and `context` packages makes sense without `framework` package. I think they are framework's specific, and that's why I think they should stay inside the `framework` package.

**Comment by xh3b4sd** [comment]
I think keeping packages inside other packages makes sense in case it is like a private sub package and not used outside the outer package. We use these packages though everywhere in our operators and not only inside the framework package. That is why I think it is valid to have this flat structure.

**Comment by kopiczko** [comment]
As I stated above I think different. I like when package is like a project that makes sense on it's own. When you are fresh to the project you have no clue that `resource` is actually `framework` component.

I don't block this PR, but I don't approve it either. Let's see what @JosephSalisbury has to say.

**Comment by xh3b4sd** [comment]
Please have a look again. I moved the resource and context packages to the framework package. 

```
$ tree -L 2 -d
.
├── client
│   ├── crdclient
│   └── k8s
├── crd
│   └── fake
├── framework
│   ├── context
│   └── resource
├── informer
├── tpr
└── vendor
    ├── github.com
    ├── golang.org
    ├── gopkg.in
    └── k8s.io
```

**Pull request merged**
