### PR TITLE
merges controller and resource sets

### PR DESCRIPTION
**Pull request by xh3b4sd**
Towards https://github.com/giantswarm/giantswarm/issues/3664.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I think we should have a little project for this to get over it together so we prevent vendor update hustle for others. Who wants to chime in from @giantswarm/sig-operator?

**Comment by MarcelMue** [comment]
I could take a few operators I work with anyway. `chart-operator`,`cluster-operator` and `release-operator`.

**Comment by xh3b4sd** [comment]
Do `release-operator` please. Like now would be nice. I cover the others.

**Comment by MarcelMue** [comment]
Ack

**Comment by xh3b4sd** [comment]
Merging this and getting the vendor PRs going.

**Pull request merged**
