### PR TITLE
removed crd package

### PR DESCRIPTION
**Pull request by xh3b4sd**
We have the types now in https://github.com/giantswarm/apiextensions.

### CODE REVIEW

**Comment by kopiczko** [comment]
Did you try to run integration tests? I think they may have some dependencies to `fake` package.

**Comment by xh3b4sd** [comment]
They fail right now. Will take care.

**Comment by xh3b4sd** [comment]
Integration tests fixed. 

```
$ go test -tags integration ./informer
ok  	github.com/giantswarm/operatorkit/informer	24.154s
```

**Comment by xh3b4sd** [comment]
Going with this.

**Pull request merged**
