### PR TITLE
consolidate resource package location

### PR DESCRIPTION
**Pull request by xh3b4sd**
I want to suggest something that might be controversial. We have currently two different `resource` packages. Recent conversations revealed that we should align these and have all resource implementations in one place. The proposed directory structure looks like the following. Let's discuss and see what we can do to improve the situation. 

```
├── controller
│   ├── context
│   └── integration
├── resource
│   ├── k8s
│   │   ├── configmapresource
│   │   └── secretresource
│   └── wrapper
│       ├── internal
│       ├── metricsresource
│       └── retryresource
```

### CODE REVIEW

**Comment by tuommaki** [comment]
I don't like the repetition of `resource` in the package name when the parent level directory refers to it and the type inside corresponding package is also `Resource`. Feels like too much repetition there. Otherwise I'm fine moving resource specific code under `controller` to top level one.

The `secret` package I'd make an exception and use plural there as otherwise it's confusing and misleading: `secret.Resource` vs. `secrets.Resource`.

**Comment by xh3b4sd** [comment]
I just followed the naming scheme we have. Then, having `configmap` but `secrets` is not possible with my OCD. Having more consistent and explicit import names makes sense to me so far.

**Comment by xh3b4sd** [comment]
Fishing for LGTM. When there is no veto I am going to merge this.

**Comment by kopiczko** [comment]
I don't like that putting `retryresource` and `metricsresource` in resource package. I'd like to keep only resources for kubernetes objects which should be generated. I think those two may get lost otherwise. They also should have different tests and follow different patterns.

I'm fine with adding `resource` suffix.

**Comment by xh3b4sd** [comment]
What I want to aim for is to have all resources in one place. I do not see why we should have them put into different locations.

**Comment by kopiczko** [comment]
They are resource wrappers and not resources on their own. They are also pretty magical. I'd be fine with having a separate package for them. Maybe `resourcewrapper`? I don't want to mix those two things because it will be burden from a maintenance standpoint.

**Comment by xh3b4sd** [comment]
What about having `resource/k8s` for your generated resources and `resource/wrapper` for retry and metrics?

**Comment by kopiczko** [comment]
> What about having `resource/k8s` for your generated resources and `resource/wrapper` for retry and metrics?

Works for me 👍

**Comment by xh3b4sd** [comment]
I pushed changes as discussed and updated the PR description with the layout example. Good to go now?

**Comment by xh3b4sd** [comment]
Sorted.

**Pull request merged**
