### PR TITLE
Add object meta to pause annotation related logs

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I am not sure what the objective is with this PR. The title suggests to pause logs. I understand this as logs not being emitted anymore. But somehow the changes suggest only some refactoring and I am unclear about its purpose.

**Comment by kopiczko** [comment]
> I understand this as logs not being emitted anymore. But somehow the changes suggest only some refactoring and I am unclear about its purpose.

Logs are emitted. They have extra object and version keys (set earlier with the logger meta). Also the annotation and its value is printed in the logs for debugging purposes.

I'm checking if I implemented things correctly and this log doesn't contain enough information:

```json
{
    "caller": "github.com/giantswarm/operatorkit/v4/pkg/controller/controller.go:472",
    "controller": "app-operator",
    "level": "debug",
    "loop": "461",
    "message": "found pause annotation",
    "time": "2021-01-05T12:25:05.156216+00:00"
}

```

**Comment by kopiczko** [comment]
Now the log looks like:

```json
{
    "caller": "github.com/giantswarm/operatorkit/v4/pkg/controller/controller.go:482",
    "controller": "app-operator",
    "level": "debug",
    "loop": "52",
    "message": "cancelling reconciliation due to pause annotation `app-operator.giantswarm.io/paused` set to `true`",
    "object": "/apis/application.giantswarm.io/v1alpha1/namespaces/giantswarm/apps/app-operator-unique",
    "time": "2021-01-05T12:28:26.256433+00:00",
    "version": "276975585"
}
```

**Comment by xh3b4sd** [comment]
Now I get it. "pause logs" is a noun. I read "pause" as verb and was baffled. 😂

**Review by xh3b4sd — APPROVED** [review]

**Comment by kopiczko** [comment]
I updated the title to hopefully clarify that a bit.

**Review by rossf7 — APPROVED** [review]

**Review by MarcelMue — APPROVED** [review]

**Review by kubasobon — APPROVED** [review]
Nice. Makes sense, since we're introducing yet another pause annotation.

**Pull request merged**
