### PR TITLE
Update k8s deps to v1.18.9

### PR DESCRIPTION
**Pull request by fiunchinho**
## Checklist

- [X] Update changelog in CHANGELOG.md.
- [ ] Update roadmap in ROADMAP.md.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
I wanted to do this automatically by tweaking our dependabot config in `devctl`. The ignore rule for k8s deps there is `>=0.17.0`. In order to get patches again for our currently used versions we should set this to `>=0.19.0`.

**Comment by fiunchinho** [comment]
> I wanted to do this automatically by tweaking our dependabot config in `devctl`. The ignore rule for k8s deps there is `>=0.17.0`. In order to get patches again for our currently used versions we should set this to `>=0.19.0`. I started playing around with it but dependabot acted up and took hours to get itself together again.

do you want me to close this PR so you fix it with dependabot then?

**Comment by xh3b4sd** [comment]
Let's close this one here and we sort it automatically. If the dependabot tweaking does not work we can reopen here and merge still.

**Comment by xh3b4sd** [comment]
For the record, the automation did not work so we have to do this manually for now. Thank you for the PR. I will just merge it now.

**Pull request merged**
