### PR TITLE
Fixes duplicate metrics

### PR DESCRIPTION
**Pull request by JosephSalisbury**
Towards https://github.com/giantswarm/giantswarm/issues/4551

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
hitting:
```
* collected metric "operatorkit_informer_deletion_timestamp" { label:<name:"kind" value:"" > label:<name:"name" value:
"joe-test-service" > label:<name:"namespace" value:"default" > gauge:<value:1.54151506e+09 > } was collected before wi
th the same name and label values
* collected metric "operatorkit_informer_creation_timestamp" { label:<name:"kind" value:"" > label:<name:"name" value:
"joe-test-service" > label:<name:"namespace" value:"default" > gauge:<value:1.541515063e+09 > } was collected before w
ith the same name and label values
* collected metric "operatorkit_informer_deletion_timestamp" { label:<name:"kind" value:"" > label:<name:"name" value:
"joe-test-service" > label:<name:"namespace" value:"default" > gauge:<value:1.541515064e+09 > } was collected before w
ith the same name and label values
* collected metric "operatorkit_informer_deletion_timestamp" { label:<name:"kind" value:"" > label:<name:"name" value:
"joe-test-service" > label:<name:"namespace" value:"default" > gauge:<value:1.541515064e+09 > } was collected before w
ith the same name and label values
```
in test

**Comment by JosephSalisbury** [comment]
So, we need to take care of deletion timestamps as well

**Comment by xh3b4sd** [comment]
I do not want to step on anybodies toes but after checking the PR tonight I wanted to suggest something. Please see https://github.com/giantswarm/operatorkit/pull/249. Lets just talk tomorrow. <3

**Comment by xh3b4sd** [comment]
@JosephSalisbury I merged my PR in here. When you are ready to go feel free to merge and do your thing. I am done here.

**Comment by JosephSalisbury** [comment]
Thanks buddy <3

**Comment by JosephSalisbury** [comment]
@giantswarm/sig-operator @giantswarm/sig-monitoring RFR

**Comment by xh3b4sd** [comment]
I wrote some of the code. I would not like to approve it. My other PR I merged in here got already approved though. I would actually just merge it.

**Comment by JosephSalisbury** [comment]
I was hoping another warm body would give an approve, just to keep it above board :D

**Comment by JosephSalisbury** [comment]
https://thumbs.gfycat.com/FrayedWelcomeAfricanrockpython-size_restricted.gif

**Pull request merged**
